"""
compatibility_check.py
========================
Validates cross-dataset feature alignment between Severson and HUST
feature matrices and generates compatibility_report.md.

Run after extract_features.py has produced all four feature files.
"""

import os
import pickle
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")  # non-interactive backend
import matplotlib.pyplot as plt

WORKSPACE = "/home/godkiller/Documents/tata"

SEV_FEAT  = os.path.join(WORKSPACE, "severson_features.pkl")
HUST_FEAT = os.path.join(WORKSPACE, "hust_features.pkl")
REPORT    = os.path.join(WORKSPACE, "compatibility_report.md")
PLOTS_DIR = os.path.join(WORKSPACE, "plots")
os.makedirs(PLOTS_DIR, exist_ok=True)

TEMP_COLS = ["Tavg_mean", "Tmax_max", "Tmin_min", "Tavg_100"]

NUMERIC_FEATURES = [
    "QD_100", "IR_cycle2", "IR_cycle100", "IR_diff",
    "dVdQ_var_10", "dVdQ_var_100", "dVdQ_var_diff",
    "I_var_10", "I_var_100", "I_var_diff",
    "chargetime_s_mean_2to6", "fade_slope", "fade_intercept",
]


def range_overlap(a_min, a_max, b_min, b_max):
    lo = max(a_min, b_min)
    hi = min(a_max, b_max)
    overlap = max(0, hi - lo)
    total   = max(a_max, b_max) - min(a_min, b_min)
    return overlap / total if total > 0 else 0.0


def plot_distributions(sev_df, hust_df, feature, out_path):
    fig, ax = plt.subplots(figsize=(7, 4))
    s = sev_df[feature].dropna()
    h = hust_df[feature].dropna()
    if len(s):
        ax.hist(s.values, bins=20, alpha=0.6, label="Severson", color="#4C72B0", density=True)
    if len(h):
        ax.hist(h.values, bins=20, alpha=0.6, label="HUST",     color="#DD8452", density=True)
    ax.set_title(f"Distribution: {feature}", fontsize=12)
    ax.set_xlabel(feature)
    ax.set_ylabel("Density")
    ax.legend()
    plt.tight_layout()
    plt.savefig(out_path, dpi=120)
    plt.close(fig)


def main():
    sev_df  = pd.read_pickle(SEV_FEAT)
    hust_df = pd.read_pickle(HUST_FEAT)

    print(f"Severson: {sev_df.shape}  |  HUST: {hust_df.shape}")

    lines = []
    lines.append("# Cross-Dataset Compatibility Report\n")
    lines.append(f"Generated by `compatibility_check.py`\n")
    lines.append(f"- **Severson cells**: {len(sev_df)}\n")
    lines.append(f"- **HUST cells**: {len(hust_df)}\n\n")

    # ── Shape & NaN summary ────────────────────────────────────
    lines.append("## Feature Matrix Summary\n")
    lines.append("| Dataset | Shape | NaN counts |\n")
    lines.append("|---------|-------|------------|\n")
    sev_nans  = sev_df[NUMERIC_FEATURES].isna().sum().to_dict()
    hust_nans = hust_df[NUMERIC_FEATURES].isna().sum().to_dict()
    lines.append(f"| Severson | {sev_df.shape} | {sev_nans} |\n")
    lines.append(f"| HUST     | {hust_df.shape} | {hust_nans} |\n\n")

    # ── Per-feature range comparison ───────────────────────────
    lines.append("## Per-Feature Range Comparison\n")
    lines.append("| Feature | Sev Min | Sev Max | HUST Min | HUST Max | Overlap % | Status |\n")
    lines.append("|---------|---------|---------|----------|----------|-----------|--------|\n")

    plot_paths = []
    for feat in NUMERIC_FEATURES:
        s = sev_df[feat].dropna()
        h = hust_df[feat].dropna()

        if len(s) == 0 or len(h) == 0:
            lines.append(f"| `{feat}` | — | — | — | — | — | ⚠️ No data in one dataset |\n")
            continue

        s_min, s_max = float(s.min()), float(s.max())
        h_min, h_max = float(h.min()), float(h.max())
        ov = range_overlap(s_min, s_max, h_min, h_max)

        if ov >= 0.8:
            status = "✅ Good overlap"
        elif ov >= 0.5:
            status = "⚠️ Partial overlap"
        else:
            status = "❌ Poor overlap"

        lines.append(f"| `{feat}` | {s_min:.4f} | {s_max:.4f} | {h_min:.4f} | {h_max:.4f} | {ov:.1%} | {status} |\n")

        # Plot
        plot_path = os.path.join(PLOTS_DIR, f"{feat}_dist.png")
        plot_distributions(sev_df, hust_df, feat, plot_path)
        plot_paths.append((feat, plot_path))

    lines.append("\n")

    # ── Temperature note ───────────────────────────────────────
    lines.append("## Temperature Features\n")
    lines.append("> ⚠️ Temperature columns (`Tavg_mean`, `Tmax_max`, `Tmin_min`, `Tavg_100`) are **not available** in the HUST dataset.\n")
    lines.append("> These are set to `NaN` for all HUST cells.\n")
    lines.append("> Krishiv must use the **`_no_temp`** feature matrix variants when training cross-dataset models.\n\n")

    # ── IR note ────────────────────────────────────────────────
    lines.append("## Internal Resistance (IR) Note\n")
    lines.append("> ⚠️ HUST discharge data begins with current already flowing (no pre-load rest period).\n")
    lines.append("> DC IR estimation via the voltage step method (`ΔV/ΔI`) is not feasible for HUST.\n")
    lines.append("> All HUST `IR_cycle2`, `IR_cycle100`, and `IR_diff` values are `NaN`.\n")
    lines.append("> IR features should be **excluded** from any cross-dataset model input.\n\n")

    # ── Fade slope distribution note ───────────────────────────
    lines.append("## Capacity Fade Slope\n")
    sev_slope_neg = (sev_df["fade_slope"] < 0).mean()
    hust_slope_neg = (hust_df["fade_slope"] < 0).mean()
    lines.append(f"- Severson cells with negative `fade_slope`: **{sev_slope_neg:.1%}**\n")
    lines.append(f"- HUST cells with negative `fade_slope`: **{hust_slope_neg:.1%}**\n")
    lines.append("> Over cycles 2–100, HUST cells are largely stable (early-life plateau), so some cells show near-zero or positive slopes — physically consistent.\n\n")

    # ── Recommended feature set ────────────────────────────────
    lines.append("## Recommended Cross-Dataset Feature Set\n")
    lines.append("Based on availability and range overlap, the following features are recommended for joint Severson+HUST training:\n\n")
    recommended = [
        "QD_100", "dVdQ_var_10", "dVdQ_var_100", "dVdQ_var_diff",
        "I_var_10", "I_var_100", "I_var_diff",
        "chargetime_s_mean_2to6", "fade_slope", "fade_intercept",
    ]
    excluded = ["IR_cycle2", "IR_cycle100", "IR_diff"] + TEMP_COLS
    for f in recommended:
        lines.append(f"- ✅ `{f}`\n")
    lines.append("\nFeatures to **exclude** from cross-dataset models:\n")
    for f in excluded:
        lines.append(f"- ❌ `{f}` — not available or incompatible for HUST\n")

    lines.append("\n## Distribution Plots\n")
    for feat, path in plot_paths:
        lines.append(f"![{feat}]({path})\n\n")

    with open(REPORT, "w") as fh:
        fh.writelines(lines)

    print(f"\n✅ Compatibility report written to: {REPORT}")
    print(f"   Distribution plots saved to: {PLOTS_DIR}/")


if __name__ == "__main__":
    main()
